"""frame count on ai_usage

Revision ID: 00a4e29500c7
Revises: f8a5e18553e8
Create Date: 2026-07-27 11:52:48.116828
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "00a4e29500c7"
down_revision: str | None = "f8a5e18553e8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ai_usage", sa.Column("frame_count", sa.Integer(), server_default="0", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ai_usage", "frame_count")
    # ### end Alembic commands ###
