"""storage archive integrations

Revision ID: 17e71ee45ce1
Revises: a08d9dd44e7a
Create Date: 2026-07-27 10:16:45.208443
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "17e71ee45ce1"
down_revision: str | None = "a08d9dd44e7a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "storage_integration_settings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("s3_enabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("s3_bucket", sa.Text(), nullable=True),
        sa.Column("s3_region", sa.Text(), nullable=True),
        sa.Column("s3_prefix", sa.Text(), nullable=True),
        sa.Column("encrypted_s3_access_key_id", sa.Text(), nullable=True),
        sa.Column("encrypted_s3_secret_access_key", sa.Text(), nullable=True),
        sa.Column("google_drive_enabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("google_drive_client_id", sa.Text(), nullable=True),
        sa.Column("encrypted_google_drive_client_secret", sa.Text(), nullable=True),
        sa.Column("encrypted_google_drive_refresh_token", sa.Text(), nullable=True),
        sa.Column("google_drive_folder_id", sa.Text(), nullable=True),
        sa.Column("onedrive_enabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("onedrive_client_id", sa.Text(), nullable=True),
        sa.Column("encrypted_onedrive_client_secret", sa.Text(), nullable=True),
        sa.Column("encrypted_onedrive_refresh_token", sa.Text(), nullable=True),
        sa.Column("onedrive_folder_path", sa.Text(), nullable=True),
        sa.Column("pending_oauth_provider", sa.Text(), nullable=True),
        sa.Column("pending_oauth_state", sa.Text(), nullable=True),
        sa.Column("pending_oauth_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_storage_integration_settings")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("storage_integration_settings")
    # ### end Alembic commands ###
