"""add blink sync tuning settings

Revision ID: 262227ff21b8
Revises: 394b8092a6cc
Create Date: 2026-07-26 22:28:50.921076
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "262227ff21b8"
down_revision: str | None = "394b8092a6cc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "app_settings", sa.Column("blink_sync_interval_seconds", sa.Integer(), nullable=True)
    )
    op.add_column("app_settings", sa.Column("blink_initial_sync_days", sa.Integer(), nullable=True))
    op.add_column(
        "app_settings", sa.Column("blink_auto_analyze_limit", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("app_settings", "blink_auto_analyze_limit")
    op.drop_column("app_settings", "blink_initial_sync_days")
    op.drop_column("app_settings", "blink_sync_interval_seconds")
    # ### end Alembic commands ###
