"""live view and security feed settings

Revision ID: 394b8092a6cc
Revises: 3d4b49c58411
Create Date: 2026-07-26 17:04:34.067896
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '394b8092a6cc'
down_revision: str | None = '3d4b49c58411'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_feed_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('camera_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('columns', sa.Integer(), server_default='2', nullable=False),
    sa.Column('refresh_interval_seconds', sa.Integer(), server_default='20', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_feed_settings'))
    )
    op.create_table('live_view_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('default_camera_id', sa.UUID(), nullable=True),
    sa.Column('auto_refresh_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('auto_refresh_interval_seconds', sa.Integer(), server_default='10', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['default_camera_id'], ['cameras.id'], name=op.f('fk_live_view_settings_default_camera_id_cameras'), ondelete='set null'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_live_view_settings'))
    )
    op.add_column('cameras', sa.Column('preview_path', sa.Text(), nullable=True))
    op.add_column('cameras', sa.Column('preview_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('default_landing_page', sa.Enum('LIBRARY', 'SECURITY_FEED', name='user_landing_page', native_enum=False, length=20), server_default='LIBRARY', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'default_landing_page')
    op.drop_column('cameras', 'preview_updated_at')
    op.drop_column('cameras', 'preview_path')
    op.drop_table('live_view_settings')
    op.drop_table('security_feed_settings')
    # ### end Alembic commands ###
