"""add pending oauth code verifier

Revision ID: 456ad39cdc83
Revises: bf5fefd1ca4c
Create Date: 2026-08-10 12:44:02.155211
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '456ad39cdc83'
down_revision: str | None = 'bf5fefd1ca4c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storage_integration_settings', sa.Column('pending_oauth_code_verifier', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('storage_integration_settings', 'pending_oauth_code_verifier')
    # ### end Alembic commands ###
