"""biometrics: people, face embeddings, recognized faces

Revision ID: 563b2434dc8e
Revises: 7766309ccbc3
Create Date: 2026-07-25 21:10:57.005274
"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op


revision: str = '563b2434dc8e'
down_revision: str | None = '7766309ccbc3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # First real use of pgvector in this codebase — the image has shipped
    # the extension since day one (see docs/ARCHITECTURE.md) but nothing
    # activated it until the face_embeddings.embedding column below.
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biometrics_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('model_pack', sa.Enum('BUFFALO_SC', 'BUFFALO_S', 'BUFFALO_M', 'BUFFALO_L', name='biometrics_model_pack', native_enum=False), server_default='BUFFALO_L', nullable=False),
    sa.Column('execution_provider_preference', sa.Enum('AUTO', 'CPU', name='biometrics_execution_provider_preference', native_enum=False), server_default='AUTO', nullable=False),
    sa.Column('recognition_threshold', sa.Float(), server_default='0.4', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biometrics_settings'))
    )
    op.create_table('people',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('thumbnail_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_people'))
    )
    op.create_table('face_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=False),
    sa.Column('source_clip_id', sa.UUID(), nullable=True),
    sa.Column('source_frame_seconds', sa.Float(), nullable=True),
    sa.Column('thumbnail_path', sa.Text(), nullable=False),
    sa.Column('is_negative', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_face_embeddings_person_id_people'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['source_clip_id'], ['clips.id'], name=op.f('fk_face_embeddings_source_clip_id_clips'), ondelete='set null'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_face_embeddings'))
    )
    op.create_index('ix_face_embeddings_person_id', 'face_embeddings', ['person_id'], unique=False)
    op.create_table('recognized_faces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clip_id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=True),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_recognized_faces_analysis_id_analyses'), ondelete='set null'),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], name=op.f('fk_recognized_faces_clip_id_clips'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_recognized_faces_person_id_people'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recognized_faces')),
    sa.UniqueConstraint('clip_id', 'person_id', name='uq_recognized_faces_clip_person')
    )
    op.create_index('ix_recognized_faces_person_id', 'recognized_faces', ['person_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recognized_faces_person_id', table_name='recognized_faces')
    op.drop_table('recognized_faces')
    op.drop_index('ix_face_embeddings_person_id', table_name='face_embeddings')
    op.drop_table('face_embeddings')
    op.drop_table('people')
    op.drop_table('biometrics_settings')
    # ### end Alembic commands ###
