"""blink accounts cameras clips and app settings

Revision ID: 6d7933522a55
Revises: 14273b7c6f0a
Create Date: 2026-07-25 01:28:25.170095
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '6d7933522a55'
down_revision: str | None = '14273b7c6f0a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('storage_dir', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_settings'))
    )
    op.create_table('blink_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('encrypted_username', sa.Text(), nullable=False),
    sa.Column('encrypted_password', sa.Text(), nullable=False),
    sa.Column('encrypted_token_data', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_2FA', 'ACTIVE', 'ERROR', name='blink_account_status', native_enum=False, length=20), server_default='active', nullable=False),
    sa.Column('last_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blink_accounts'))
    )
    op.create_table('cameras',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('blink_account_id', sa.UUID(), nullable=False),
    sa.Column('blink_camera_id', sa.Text(), nullable=False),
    sa.Column('blink_network_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('camera_type', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('battery', sa.Text(), nullable=True),
    sa.Column('thumbnail_path', sa.Text(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['blink_account_id'], ['blink_accounts.id'], name=op.f('fk_cameras_blink_account_id_blink_accounts'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cameras')),
    sa.UniqueConstraint('blink_account_id', 'blink_camera_id', name='uq_cameras_blink_camera')
    )
    op.create_index(op.f('ix_cameras_blink_account_id'), 'cameras', ['blink_account_id'], unique=False)
    op.create_table('clips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('blink_clip_id', sa.Text(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_on_blink', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('storage_backend', sa.Enum('LOCAL', name='clip_storage_backend', native_enum=False, length=20), server_default='local', nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=True),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('thumbnail_generated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_clips_camera_id_cameras'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clips')),
    sa.UniqueConstraint('camera_id', 'blink_clip_id', name='uq_clips_blink_clip')
    )
    op.create_index('ix_clips_camera_id', 'clips', ['camera_id'], unique=False)
    op.create_index('ix_clips_recorded_at', 'clips', ['recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_clips_recorded_at', table_name='clips')
    op.drop_index('ix_clips_camera_id', table_name='clips')
    op.drop_table('clips')
    op.drop_index(op.f('ix_cameras_blink_account_id'), table_name='cameras')
    op.drop_table('cameras')
    op.drop_table('blink_accounts')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
