"""AI analysis, vehicles, alerts

Revision ID: 7766309ccbc3
Revises: 6d7933522a55
Create Date: 2026-07-25 08:04:18.133641
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '7766309ccbc3'
down_revision: str | None = '6d7933522a55'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('tier1_provider', sa.Enum('OPENAI', 'ANTHROPIC', 'OLLAMA', 'OLLAMA_CLOUD', 'MOONDREAM', 'MOONDREAM_CLOUD', name='ai_provider_kind', native_enum=False), nullable=True),
    sa.Column('tier1_model', sa.Text(), nullable=True),
    sa.Column('tier1_encrypted_api_key', sa.Text(), nullable=True),
    sa.Column('tier1_base_url', sa.Text(), nullable=True),
    sa.Column('tier2_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('tier2_provider', sa.Enum('OPENAI', 'ANTHROPIC', 'OLLAMA', 'OLLAMA_CLOUD', 'MOONDREAM', 'MOONDREAM_CLOUD', name='ai_provider_kind', native_enum=False), nullable=True),
    sa.Column('tier2_model', sa.Text(), nullable=True),
    sa.Column('tier2_encrypted_api_key', sa.Text(), nullable=True),
    sa.Column('tier2_base_url', sa.Text(), nullable=True),
    sa.Column('keyframes_per_clip', sa.Integer(), server_default='4', nullable=False),
    sa.Column('tier2_suspicion_threshold', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('feedback_context_count', sa.Integer(), server_default='5', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_settings'))
    )
    op.create_table('alert_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('discord_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('encrypted_discord_webhook_url', sa.Text(), nullable=True),
    sa.Column('slack_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('encrypted_slack_webhook_url', sa.Text(), nullable=True),
    sa.Column('smtp_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('smtp_host', sa.Text(), nullable=True),
    sa.Column('smtp_port', sa.Integer(), server_default='587', nullable=False),
    sa.Column('smtp_username', sa.Text(), nullable=True),
    sa.Column('encrypted_smtp_password', sa.Text(), nullable=True),
    sa.Column('smtp_use_tls', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('smtp_from_address', sa.Text(), nullable=True),
    sa.Column('smtp_to_addresses', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('alert_on_suspicious_clip', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('suspicion_alert_threshold', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('alert_on_vehicle_proximity', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('quiet_hours_start', sa.Time(), nullable=True),
    sa.Column('quiet_hours_end', sa.Time(), nullable=True),
    sa.Column('dedup_window_minutes', sa.Integer(), server_default='15', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_settings'))
    )
    op.create_table('camera_baselines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('hourly_entity_counts', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('total_observations', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_camera_baselines_camera_id_cameras'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_camera_baselines')),
    sa.UniqueConstraint('camera_id', name=op.f('uq_camera_baselines_camera_id'))
    )
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('outline_points', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('reference_frame_path', sa.Text(), nullable=True),
    sa.Column('estimated_length_feet', sa.Float(), server_default='15.0', nullable=False),
    sa.Column('distance_threshold_feet', sa.Float(), server_default='6.0', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_vehicles_camera_id_cameras'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicles')),
    sa.UniqueConstraint('camera_id', name='uq_vehicles_camera')
    )
    op.create_table('analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clip_id', sa.UUID(), nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('suspicion_score', sa.Float(), nullable=False),
    sa.Column('suspicion_label', sa.Enum('ROUTINE', 'UNCERTAIN', 'SUSPICIOUS', name='suspicion_label', native_enum=False), nullable=False),
    sa.Column('tier', sa.Enum('TIER1', 'TIER2', name='analysis_tier', native_enum=False), nullable=False),
    sa.Column('escalated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('tier1_provider', sa.Enum('OPENAI', 'ANTHROPIC', 'OLLAMA', 'OLLAMA_CLOUD', 'MOONDREAM', 'MOONDREAM_CLOUD', name='ai_provider_kind', native_enum=False), nullable=True),
    sa.Column('tier1_model', sa.Text(), nullable=True),
    sa.Column('tier2_provider', sa.Enum('OPENAI', 'ANTHROPIC', 'OLLAMA', 'OLLAMA_CLOUD', 'MOONDREAM', 'MOONDREAM_CLOUD', name='ai_provider_kind', native_enum=False), nullable=True),
    sa.Column('tier2_model', sa.Text(), nullable=True),
    sa.Column('detected_entities', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('vehicle_proximity', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], name=op.f('fk_analyses_clip_id_clips'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analyses'))
    )
    op.create_index('ix_analyses_clip_current', 'analyses', ['clip_id', 'is_current'], unique=False)
    op.create_index('ix_analyses_clip_id', 'analyses', ['clip_id'], unique=False)
    op.create_table('proximity_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('clip_id', sa.UUID(), nullable=False),
    sa.Column('distance_feet', sa.Float(), nullable=False),
    sa.Column('error_margin_feet', sa.Float(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], name=op.f('fk_proximity_events_clip_id_clips'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_proximity_events_vehicle_id_vehicles'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proximity_events'))
    )
    op.create_table('ai_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=True),
    sa.Column('clip_id', sa.UUID(), nullable=False),
    sa.Column('tier', sa.Enum('TIER1', 'TIER2', name='analysis_tier', native_enum=False), nullable=False),
    sa.Column('provider', sa.Enum('OPENAI', 'ANTHROPIC', 'OLLAMA', 'OLLAMA_CLOUD', 'MOONDREAM', 'MOONDREAM_CLOUD', name='ai_provider_kind', native_enum=False), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('completion_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=10, scale=6), server_default='0', nullable=False),
    sa.Column('latency_ms', sa.Integer(), server_default='0', nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_ai_usage_analysis_id_analyses'), ondelete='set null'),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], name=op.f('fk_ai_usage_clip_id_clips'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_usage'))
    )
    op.create_index('ix_ai_usage_created_at', 'ai_usage', ['created_at'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clip_id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=True),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('PERSON_DETECTED', 'VEHICLE_DETECTED', 'ANIMAL_DETECTED', 'PACKAGE_DETECTED', 'UNKNOWN_DETECTED', 'VEHICLE_PROXIMITY_BREACH', 'SUSPICIOUS_ACTIVITY', name='event_type', native_enum=False), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_events_analysis_id_analyses'), ondelete='set null'),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_events_camera_id_cameras'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], name=op.f('fk_events_clip_id_clips'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events')),
    sa.UniqueConstraint('clip_id', 'event_type', name='uq_events_clip_type')
    )
    op.create_index('ix_events_camera_occurred', 'events', ['camera_id', 'occurred_at'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('verdict', sa.Enum('CORRECT', 'FALSE_POSITIVE', 'FALSE_NEGATIVE', name='feedback_verdict', native_enum=False), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('applied', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_feedback_analysis_id_analyses'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_feedback_user_id_users'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback'))
    )
    op.create_index('ix_feedback_analysis_id', 'feedback', ['analysis_id'], unique=False)
    op.add_column('cameras', sa.Column('security_context', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cameras', 'security_context')
    op.drop_index('ix_feedback_analysis_id', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index('ix_events_camera_occurred', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_ai_usage_created_at', table_name='ai_usage')
    op.drop_table('ai_usage')
    op.drop_table('proximity_events')
    op.drop_index('ix_analyses_clip_id', table_name='analyses')
    op.drop_index('ix_analyses_clip_current', table_name='analyses')
    op.drop_table('analyses')
    op.drop_table('vehicles')
    op.drop_table('camera_baselines')
    op.drop_table('alert_settings')
    op.drop_table('ai_settings')
    # ### end Alembic commands ###
