"""auto archive after days delay

Revision ID: 80beafc83375
Revises: 00a4e29500c7
Create Date: 2026-07-28 05:48:08.416559
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "80beafc83375"
down_revision: str | None = "00a4e29500c7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "storage_integration_settings",
        sa.Column("auto_archive_after_days", sa.Integer(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("storage_integration_settings", "auto_archive_after_days")
    # ### end Alembic commands ###
