"""add alert on low battery

Revision ID: 89d4d3da8e54
Revises: d081b4eff606
Create Date: 2026-08-05 05:18:04.917555
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "89d4d3da8e54"
down_revision: str | None = "d081b4eff606"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "alert_settings",
        sa.Column("alert_on_low_battery", sa.Boolean(), server_default="true", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("alert_settings", "alert_on_low_battery")
    # ### end Alembic commands ###
