"""add never_mark_suspicious to people

Revision ID: a08d9dd44e7a
Revises: 262227ff21b8
Create Date: 2026-07-26 23:36:17.745996
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a08d9dd44e7a"
down_revision: str | None = "262227ff21b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "people",
        sa.Column("never_mark_suspicious", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("people", "never_mark_suspicious")
    # ### end Alembic commands ###
