"""add battery events table

Revision ID: aa0ccd4c9cde
Revises: 89d4d3da8e54
Create Date: 2026-08-05 05:22:04.616618
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "aa0ccd4c9cde"
down_revision: str | None = "89d4d3da8e54"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "battery_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("camera_id", sa.UUID(), nullable=False),
        sa.Column("battery", sa.Text(), nullable=True),
        sa.Column("previous_battery", sa.Text(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["camera_id"],
            ["cameras.id"],
            name=op.f("fk_battery_events_camera_id_cameras"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_battery_events")),
    )
    op.create_index(
        "ix_battery_events_camera_id_occurred_at",
        "battery_events",
        ["camera_id", "occurred_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_battery_events_camera_id_occurred_at", table_name="battery_events")
    op.drop_table("battery_events")
    # ### end Alembic commands ###
