"""local storage quota

Revision ID: b22b40a2cd07
Revises: 80beafc83375
Create Date: 2026-07-28 06:06:06.437496
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b22b40a2cd07"
down_revision: str | None = "80beafc83375"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "app_settings", sa.Column("local_storage_quota_bytes", sa.BigInteger(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("app_settings", "local_storage_quota_bytes")
    # ### end Alembic commands ###
