"""thumbnail path column

Revision ID: b404a792128c
Revises: b22b40a2cd07
Create Date: 2026-07-28 06:38:47.260974
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b404a792128c"
down_revision: str | None = "b22b40a2cd07"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("clips", sa.Column("thumbnail_path", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clips", "thumbnail_path")
    # ### end Alembic commands ###
