"""add security feed refresh mode

Revision ID: bf5fefd1ca4c
Revises: aa0ccd4c9cde
Create Date: 2026-08-10 11:34:43.898988
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'bf5fefd1ca4c'
down_revision: str | None = 'aa0ccd4c9cde'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('security_feed_settings', sa.Column('refresh_mode', sa.Enum('INTERVAL', 'MOTION', name='security_feed_refresh_mode', native_enum=False, length=10), server_default='INTERVAL', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('security_feed_settings', 'refresh_mode')
    # ### end Alembic commands ###
