"""biometrics model download status

Revision ID: d081b4eff606
Revises: 5030946cd741
Create Date: 2026-08-03 18:24:19.149088
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "d081b4eff606"
down_revision: str | None = "5030946cd741"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "biometrics_settings",
        sa.Column(
            "model_download_status",
            sa.Enum(
                "IDLE",
                "DOWNLOADING",
                "READY",
                "ERROR",
                name="biometrics_model_download_status",
                native_enum=False,
            ),
            server_default="IDLE",
            nullable=False,
        ),
    )
    op.add_column(
        "biometrics_settings", sa.Column("model_download_error", sa.Text(), nullable=True)
    )
    op.add_column(
        "biometrics_settings",
        sa.Column(
            "model_download_providers",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("biometrics_settings", "model_download_providers")
    op.drop_column("biometrics_settings", "model_download_error")
    op.drop_column("biometrics_settings", "model_download_status")
    # ### end Alembic commands ###
