"""sync modules and local storage items

Revision ID: d81263dff5a9
Revises: b404a792128c
Create Date: 2026-07-28 22:17:00.373788
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d81263dff5a9"
down_revision: str | None = "b404a792128c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sync_modules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("blink_account_id", sa.UUID(), nullable=False),
        sa.Column("network_id", sa.Text(), nullable=False),
        sa.Column("sync_id", sa.Text(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("serial", sa.Text(), nullable=True),
        sa.Column("firmware_version", sa.Text(), nullable=True),
        sa.Column("is_physical_hub", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("armed", sa.Boolean(), nullable=True),
        sa.Column("online", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("local_storage_compatible", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("local_storage_enabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("local_storage_active", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("local_storage_manifest_id", sa.Text(), nullable=True),
        sa.Column(
            "local_storage_status",
            sa.Enum(
                "IDLE",
                "REFRESHING",
                "ERROR",
                name="sync_module_local_storage_status",
                native_enum=False,
                length=20,
            ),
            server_default="IDLE",
            nullable=False,
        ),
        sa.Column("local_storage_manifest_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("local_storage_manifest_refreshed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("local_storage_last_error", sa.Text(), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["blink_account_id"],
            ["blink_accounts.id"],
            name=op.f("fk_sync_modules_blink_account_id_blink_accounts"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_modules")),
        sa.UniqueConstraint("blink_account_id", "network_id", name="uq_sync_modules_network"),
    )
    op.create_index(
        op.f("ix_sync_modules_blink_account_id"), "sync_modules", ["blink_account_id"], unique=False
    )
    op.create_table(
        "sync_module_local_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sync_module_id", sa.UUID(), nullable=False),
        sa.Column("camera_id", sa.UUID(), nullable=True),
        sa.Column("camera_name", sa.Text(), nullable=False),
        sa.Column("blink_item_id", sa.BigInteger(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("present_on_device", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "AVAILABLE",
                "PREPARING",
                "DOWNLOADING",
                "DOWNLOADED",
                "ERROR",
                name="sync_module_local_item_status",
                native_enum=False,
                length=20,
            ),
            server_default="AVAILABLE",
            nullable=False,
        ),
        sa.Column("storage_path", sa.Text(), nullable=True),
        sa.Column("downloaded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["camera_id"],
            ["cameras.id"],
            name=op.f("fk_sync_module_local_items_camera_id_cameras"),
            ondelete="set null",
        ),
        sa.ForeignKeyConstraint(
            ["sync_module_id"],
            ["sync_modules.id"],
            name=op.f("fk_sync_module_local_items_sync_module_id_sync_modules"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_module_local_items")),
        sa.UniqueConstraint(
            "sync_module_id", "blink_item_id", name="uq_sync_module_local_items_item"
        ),
    )
    op.create_index(
        "ix_sync_module_local_items_sync_module_id",
        "sync_module_local_items",
        ["sync_module_id"],
        unique=False,
    )
    op.add_column(
        "cameras", sa.Column("motion_enabled", sa.Boolean(), server_default="true", nullable=False)
    )
    op.add_column(
        "cameras",
        sa.Column("motion_action_type", sa.Text(), server_default="default", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cameras", "motion_action_type")
    op.drop_column("cameras", "motion_enabled")
    op.drop_index("ix_sync_module_local_items_sync_module_id", table_name="sync_module_local_items")
    op.drop_table("sync_module_local_items")
    op.drop_index(op.f("ix_sync_modules_blink_account_id"), table_name="sync_modules")
    op.drop_table("sync_modules")
    # ### end Alembic commands ###
