"""auto archive backend for new downloads

Revision ID: f8a5e18553e8
Revises: 17e71ee45ce1
Create Date: 2026-07-27 11:39:38.972728
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f8a5e18553e8"
down_revision: str | None = "17e71ee45ce1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "storage_integration_settings",
        sa.Column(
            "auto_archive_backend",
            sa.Enum(
                "LOCAL",
                "S3",
                "GOOGLE_DRIVE",
                "ONEDRIVE",
                name="storage_auto_archive_backend",
                native_enum=False,
                length=20,
            ),
            server_default="LOCAL",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("storage_integration_settings", "auto_archive_backend")
    # ### end Alembic commands ###
